export default {
	webpack(config, env, helpers, options) {
		// NOTE (cb): hook into preact cli if necessary
        // config.module.rules[4].use.splice(1, 0, {
        //     loader: "@teamsupercell/typings-for-css-modules-loader",
        //     options: {
        //         banner:
        //             "// This file is automatically generated from your CSS. Any edits will be overwritten.",
        //         disableLocalsExport: true
        //     }
        // });

        // // Use any `index` file, not just index.js
        // config.resolve.alias["preact-cli-entrypoint"] = resolve(
        //     process.cwd(),
        //     "src",
        //     "index"
        // );

        // config.output.publicPath = '';
	},
};